### ISSUE TITLE
Raw data availablity

### ISSUE THREAD

**Issue by adimascf** [sbslee/clinpharmseq-paper#1]
Very interesting work. Thank you for making the code publicly available. Do you share your raw data  (.fastq) from this work as well?
Thank you.

**Comment by sbslee** [comment]
@adimascf,

My apology for the delayed reply! At this very moment, we don't have any plans to release the raw data. Please note that this repository already contains all the [input files](https://github.com/sbslee/clinpharmseq-paper/tree/main/pypgx-input-files) required to reproduce the analyses presented in the paper. I will let you know here when there is any change of plans.
